apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dncmehxwj-dotnet-basic
  janus-idp.io/tekton: dncmehxwj-dotnet-basic
  backstage.io/kubernetes-id: dncmehxwj-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dncmehxwj-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
